language: node_js
services:
  - docker
node_js:
  - "11.10.1"
env:
  - CYPRESS_baseUrl=http://localhost
cache: yarn
script:
  - git clone https://github.com/PracticaDS/pdes-tp-backend-practicadesapp
  - git clone https://github.com/PracticaDS/pdes-tp-practicadesapp
  - cd pdes-tp-backend-practicadesapp
  - yarn install
  - yarn start
  - cd ..
  - cd pdes-tp-practicadesapp
  - yarn install
  - yarn start
  - cd ..
  - docker-compose up -d
  - yarn run cypress:run
  - docker-compose down
  - yarn run clean
