language: node_js
services:
  - docker
node_js:
  - "11.10.1"
env:
  - CYPRESS_baseUrl=http://localhost
cache: npm
script:
  - npm run cloneAll
  - docker-compose up -d
  - npm run waitForServer
  - npm run cypress:run
  - docker-compose down
  - npm run clean
